<?php

use CG\Templates\Advertising\AdSense\AdSenseTemplate;

/**
 * @var $this AdSenseTemplate
 */
?>

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2279132360925160"
        crossorigin="anonymous"></script>

<!-- Under intro -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2279132360925160"
     data-ad-slot="3670394530"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>
