<?php
/**
 * @var bool $is_preview
 * @var string $content The block inner HTML.
 */

$allowed_blocks = array('core/paragraph');

?>

<?php if ($is_preview): ?>
    <div class="card" style="max-width: unset; color: rgb(60, 64, 67); font-size: 14px; line-height: 20px;">
        <InnerBlocks allowedBlocks="<?= esc_attr(wp_json_encode($allowed_blocks)) ?>"/>
    </div>
<?php else: ?>
    <InnerBlocks/>
<?php endif; ?>

