<?php
/**
 * @var int $post_id
 * @var bool $is_preview
 */


use CG\ContactForm\AjaxContactForm;

$ajax = admin_url('admin-ajax.php');
$action = AjaxContactForm::SEND_FORM_ACTION;

try {
    $two_digits = array(random_int(1, 5), random_int(1, 5),);
} catch (Exception $e) {
    $two_digits = array(5, 5,);
}
?>

<?php if ($is_preview): ?>
    <div style=" height: 250px; border: 1px solid #000; display: flex; justify-content: center; align-items: center;">
        <p>Formularz kontaktowy</p>
    </div>
<?php else: ?>
    <form action="<?= $ajax ?>" method="post" class="contact-form">
        <input type="hidden" name="action" value="<?= $action ?>">
        <input type="hidden" name="digit_first" value="<?= $two_digits[0] ?>">
        <input type="hidden" name="digit_second" value="<?= $two_digits[1] ?>">

        <div>
            <label for="subject">Temat *</label>
            <input id="subject" type="text" name="subject" required autocomplete="off">
        </div>

        <div>
            <label for="name">Imię i nazwisko *</label>
            <input id="name" type="text" name="name" required>
        </div>

        <div>
            <label for="email">E-mail *</label>
            <input id="email" type="email" name="email">
        </div>

        <div>
            <label for="content">Wiadomość *</label>
            <textarea id="content" rows="10" name="content" required></textarea>
        </div>

        <div>
            <div>
                <label for="recaptcha">Dodaj dwie liczby (weryfikacja anyspamowa)</label>
                <div>
                    <span><?= $two_digits[0] ?> + <?= $two_digits[1] ?> =</span>
                    <input id="recaptcha" type="number" name="recaptcha" required>
                </div>
            </div>
            <button type="submit">Wyślij</button>
        </div>

    </form>
<?php endif; ?>
