<?php

use CG\Templates\PostTile\PostTileTemplate;

/**
 * @var $this PostTileTemplate
 */
?>

<article class="post-tile">
    <a href="<?php the_permalink(); ?>" class="post-tile-image-link">
        <?php
        $id = get_thumbnail_id_from_tree();
        echo wp_get_attachment_image($id, 'post_tile', false,
            array(
                'class' => 'post-tile-image'
            )
        );
        ?>
    </a>
    <div style="display: flex; flex-direction: column; justify-content: space-between">
        <div>
            <h4 style="font-size: 1.5rem; margin: 0 0 0.8rem;line-height: 1">
                <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
            </h4>

            <?php
            $categoriesTemplate = new CG\Templates\PostTerms\PostTermsTemplate();
            $categoriesTemplate->render();
            ?>

            <div style="text-align: justify; margin-top: 0.5rem" title="<?= $this->get_title() ?>">
                <?= $this->get_excerpt() ?>
            </div>
        </div>

        <p style="margin: .5rem 0 0 0; line-height: 1;">
            <a href="<?php the_permalink(); ?>"><?= __('Read more', 'cg') ?></a>
        </p>

    </div>
</article>