<?php

use CG\Templates\FeaturedArticles\FeaturedArticlesTemplate;

/**
 * @var $this FeaturedArticlesTemplate
 */

$current_post_id = get_the_ID();
$current_post_categories = wp_get_post_categories($current_post_id);

$query = new WP_Query(array(
    'posts_per_page' => 6,
    'post_type' => 'post',
    'post__not_in' => array($current_post_id),
    'cat' => $current_post_categories
));
?>
<div class="feature-articles">
    <h2 class="title">Featured Articles</h2>

    <div class="articles">
        <?php while ($query->have_posts()): $query->the_post(); ?>
            <article class="article">
                <?php
                $id = get_thumbnail_id_from_tree();
                echo wp_get_attachment_image($id, 'article-image', false, array('class' => 'post-tile-image'));
                ?>
                <div class="article-content">
                    <h3 class="article-title" title="<?php the_title() ?>">
                        <a href="<?php the_permalink(); ?>"><?php the_title() ?></a>
                    </h3>
                    <p>
                    </p>
                </div>
            </article>
        <?php endwhile; ?>
        <?php wp_reset_postdata(); ?>
    </div>
</div>

