<?php

use CG\Templates\FeaturedArticles\FeaturedArticlesTemplate;

/**
 * @var $this FeaturedArticlesTemplate
 */

$first_query = $this->feature_article_query;
$second_query = $this->extra_feature_article_query;

?>
<div class="feature-articles">
    <h2 class="title">Featured Articles</h2>

    <div class="articles">
        <?php

        while ($first_query->have_posts()):
            $first_query->the_post();
            $this->get_article_template();
        endwhile;
        wp_reset_postdata();

        if ($second_query !== null):
            while ($second_query->have_posts()):
                $second_query->the_post();
                $this->get_article_template();
            endwhile;
            wp_reset_postdata();
        endif;

        ?>
    </div>
</div>
