<article class="article">
    <?php
    $id = get_thumbnail_id_from_tree();
    echo wp_get_attachment_image(
        $id,
        'article-image',
        false,
        array('class' => 'post-tile-image')
    );
    ?>
    <div class="article-content">
        <h3 class="article-title" title="<?php the_title() ?>">
            <a href="<?php the_permalink(); ?>"><?php the_title() ?></a>
        </h3>
        <p>
        </p>
    </div>
</article>