<?php
/**
 * @var int $post_id
 * @var bool $is_preview
 */


use CG\Plugins\ContactForm\AjaxContactForm;

$subject = get_field("92A3C1AA985D40F3A68A2D50FA4C4835");
$ajax = admin_url('admin-ajax.php');
$action = AjaxContactForm::SEND_FORM_ACTION;

try {
    $two_digits = array(random_int(1, 5), random_int(1, 5),);
} catch (Exception $e) {
    $two_digits = array(5, 5,);
}
?>

<?php if ($is_preview): ?>
    <div style=" height: 250px; border: 1px solid #000; display: flex; justify-content: center; align-items: center;">
        <p>Contact form</p>
    </div>
<?php else: ?>
    <form action="<?= $ajax ?>" method="post" class="contact-form">
        <input type="hidden" name="action" value="<?= $action ?>">
        <input type="hidden" name="digit_first" value="<?= $two_digits[0] ?>">
        <input type="hidden" name="digit_second" value="<?= $two_digits[1] ?>">

        <div>
            <label for="subject">Subject *</label>
            <input id="subject" type="text" name="subject" required autocomplete="off" value="<?= $subject ?>">
        </div>

        <div>
            <label for="name">Name *</label>
            <input id="name" type="text" name="name" required>
        </div>

        <div>
            <label for="email">E-mail address *</label>
            <input id="email" type="email" name="email" required>
        </div>

        <div>
            <label for="content">Message *</label>
            <textarea id="content" rows="10" name="content" required></textarea>
        </div>

        <div>
            <div>
                <label for="recaptcha">Add two digits (Anti-spam verification)</label>
                <div>
                    <span><?= $two_digits[0] ?> + <?= $two_digits[1] ?> =</span>
                    <input id="recaptcha" type="number" name="recaptcha" required>
                </div>
            </div>
            <button type="submit">Send</button>
        </div>

    </form>
<?php endif; ?>
