<?php

use CG\Templates\PostCategories\PostCategoriesTemplate;
use CG\Templates\RepositoryLink\RepositoryLinkTemplate;
use CG\Templates\SingleIntro\SingleIntroTemplate;

/**
 * @var $this SingleIntroTemplate
 */
?>

<header class="post-intro-container">

    <div class="post-intro">
        <div class="post-intro-content">
            <h1 class="post-intro-title"><?= get_the_title() ?></h1>
            <div class="post-intro-excerpt"><?= get_the_excerpt() ?></div>

            <?php
            $categoriesTemplate = new PostCategoriesTemplate();
            $categoriesTemplate->render();
            ?>
        </div>

        <?php
        $id = get_thumbnail_id_from_tree();
        echo wp_get_attachment_image(
            $id,
            'post_tile',
            false,
            array('class' => 'post-intro-image')
        );
        ?>
    </div>

    <?php
    $source = new RepositoryLinkTemplate();
    $source->render();
    ?>

</header>



