<?php

use CG\Integrations\Acf\Blocks\CodePreview\CodePreviewUtils;

$language_name = get_field('593D265269114F70B5E116DB58AF9BE5') ?? '';
$code = get_field('8E9300D01F9547E781F8F7DE5DCA0742') ?? '';

$show_header = get_field('7E4C8F667ABD4C4C801D703E7F95C5B8');
$header_data = get_field('BE6B8012D8D84DC2A1E0B7488560F547');
$type = $header_data['91BA2AE9587D44B3B2678890B254A752'] ?? '';
$info = $header_data['CC4A21F9F0AB429A833837B499B095F1'] ?? '';


$parsed = CodePreviewUtils::highlight($language_name, $code);
$parsed = CodePreviewUtils::highlight_lines($parsed);

?>

<div class="code-preview <?= $show_header ? 'with-header' : '' ?> <?= $type ?>">
    <?php if ($show_header): ?>
        <header>
            <div><?= $info ?></div>
            <button title="Copy to clipboard" data-action="copyCodePreview">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                    <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                </svg>
            </button>
        </header>
    <?php endif; ?>

    <pre><code class="hljs <?= $language_name ?>"><?= $parsed ?></code></pre>

</div>

